{{ if and (not .Values.demo) .Values.oathkeeper.configFileOverride.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oathkeeper.configmap.name" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels: {{- include "oathkeeper.labels" . | nindent 4 }}
data:
  "config.yaml": |
    {{- include "oathkeeper.configmap" . | nindent 4 }}
{{- end }}
