{{- if .Values.hydra.autoMigrate }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hydra.fullname" . }}-automigrate
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "hydra.labels" . | indent 4 }}
    {{- with .Values.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.deployment.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    helm.sh/hook-weight: "1"
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
spec:
  template:
    spec:
      containers:
      - name: {{ .Chart.Name }}-automigrate
        image: {{ .Values.image.repository }}:{{ include "hydra.getAlpineImage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /bin/sh
        - -c
        - |
{{ .Files.Get "files/automigrate.sh" | printf "%s" | indent 10 }}
        volumeMounts:
          - name: {{ include "hydra.name" . }}-config-volume
            mountPath: /etc/config
            readOnly: true
        env:
          - name: DSN
            valueFrom:
              secretKeyRef:
                name: {{ include "hydra.secretname" . }}
                key: dsn
          - name: NAME_ROOT
            value: {{ include "hydra.fullname" . | quote }}
          - name: NAMESPACE
            value: {{ .Release.Namespace }}
          - name: TASK_TIMEOUT
            value: "30s"
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          # Temporary. Need root to install packages
          runAsUser: 0
          allowPrivilegeEscalation: false
          privileged: false
      restartPolicy: Never
      volumes:
        - name: {{ include "hydra.name" . }}-config-volume
          configMap:
            name: {{ include "hydra.fullname" . }}-automigrate
      serviceAccountName: {{ include "hydra.fullname" . }}-automigrate
  backoffLimit: 5
{{- end }}